{% set version = "3.0.3" %}

package:
  name: rio-cogeo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rio-cogeo/rio-cogeo-{{ version }}.tar.gz
  sha256: cd7f9fbd398bad59879f429672f14620805d75a2b83a9079a10d3a2e105305d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click >=7.0
    - morecantile >=3.0,<3.1
    - numpy ~=1.15
    - pydantic
    - rasterio >=1.1

test:
  imports:
    - rio_cogeo
    - rio_cogeo.scripts
  commands:
    - pip check
    - rio cogeo --help
    - rio cogeo create --help
    - rio cogeo validate --help
  requires:
    - pip
    - boto3 >=1.2.4

about:
  home: https://github.com/cogeotiff/rio-cogeo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CloudOptimized GeoTIFF (COGEO) creation plugin for rasterio

extra:
  recipe-maintainers:
    - ocefpaf
