{% set version = "1.1.8" %}

package:
  name: rio-cogeo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rio-cogeo/rio-cogeo-{{ version }}.tar.gz
  sha256: 25fecb1ec19d685bcef961fdbfc37cb5436f377f353b4b7775755b5dd4557266

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >3.3
    - pip
  run:
    - python >3.3
    - click
    - mercantile
    - numpy >=1.15,<2
    - rasterio >=1.0.9
    - boto3 >=1.2.4
    - supermercado

test:
  imports:
    - rio_cogeo
    - rio_cogeo.scripts
  commands:
    - rio cogeo --help
    - rio cogeo create --help
    - rio cogeo validate --help

about:
  home: https://github.com/cogeotiff/rio-cogeo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CloudOptimized GeoTIFF (COGEO) creation plugin for rasterio

extra:
  recipe-maintainers:
    - ocefpaf
